#pragma once
#ifndef _UDP_CONFIG_H_
#define _UDP_CONFIG_H_

#define DEFAULT_SERVER_IP "127.0.0.1"
#define DEFAULT_ADDR_TYPE AF_INET
#define DEFAULT_RECE_FROM ADDR_ANY
#define DEFAULT_SEND_PORT 54000
#define DEFAULT_RECE_PORT 54001

#endif // !_UDP_CONFIG_H_
